spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: sa
    password:
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    show-sql: true
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/

